import Head from 'next/head'
import Navbar from '../components/Navbar'
import HomePage from '../components/Home'
import Services from '../components/Services'
import WhyUs from '../components/WhyUs'
import Team from '../components/Team'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Avenir iP Ltd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Navbar/>
      <HomePage/>
      <Services/>
      <WhyUs/>
      <Team/>
      <Footer/>
      
      {/* <HomePage/> */}

  
     

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}

    </div>
  )
}
